version: '3'
services:
  web:
    build: .
    ports:
      - "3000:3000"
  redis:
    image: "redis"
    command: ["redis-server", "--protected-mode", "no", "--daemonize", "no"]
    privileged: true

